RapidVet.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using RapidVet.Helpers;
using RapidVet.Model.Clients;
using RapidVet.Model.Clinics;
using RapidVet.Model.Finance;
using RapidVet.Model.Users;
using RapidVet.Repository;
using RapidVet.WebModels.Clients;
using RapidVet.WebModels.Finance;
using RapidVet.WebModels.Patients;
using RapidVetMembership;
using RapidVet.RapidConsts;
using RapidVet.Model.ClinicGroups;
using System.Globalization;
using System.Configuration;
using RapidVet.Repository.Clinics;
using Microsoft.AspNet.SignalR;
//using RestSharp;
//using RestSharp.Authenticators;

namespace RapidVet.Web.Controllers
{

    public class BaseController : Controller
    {
        private RapidVetUnitOfWork _rapidVetUnitOfWork;
        protected RapidVetUnitOfWork RapidVetUnitOfWork
        {
            get { return _rapidVetUnitOfWork ?? (_rapidVetUnitOfWork = new RapidVetUnitOfWork()); }
        }

        private List<TemplateKeyWords> _templateKeyWords;
        protected List<TemplateKeyWords> TemplateKeyWords
        {
            get { return _templateKeyWords ?? (_templateKeyWords = RapidVetUnitOfWork.TemplateKeyWordsRepository.GetAllTemplateKeyWords(CultureInfo.CurrentCulture.Name)); }
        }

        protected string getTemplateKeyWord(string keyword)
        {
            return TemplateKeyWords.Single(t => t.TemplateKeyWord.Equals(keyword)).KeyWord;
        }

        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            SetCurrentUserViewBag();

            //Load Last client to View Bag
            if (User.Identity.IsAuthenticated && !CurrentUser.IsAdministrator)
            {
                ViewBag.LastClients = RapidVetUnitOfWork.LastClientRepository.GetLastClients(CurrentUser.Id,
                                                                                             CurrentUser.ActiveClinicId) ?? new List<RapidVet.Model.Clients.LastClient>().AsQueryable();
            }
            base.OnActionExecuted(filterContext);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            var savePath = System.Configuration.ConfigurationManager.AppSettings["LOG_PATH"];
            if (savePath != null)
                BaseLogger.LogWriter.WriteExPath(filterContext.Exception, savePath);

            if (filterContext.Exception is SecurityException)
            {
                if (filterContext.ExceptionHandled)
                {
                    return;
                }
                if (_currentUser != null)
                {
                    ConcurrentUserInfo.RemoveByUserName(CurrentUser.Username);
                }
                FormsAuthentication.SignOut();
                filterContext.Result = new ViewResult
                {
                    ViewName = "~/Views/Base/SecurityExceptionResult.cshtml"
                };
                filterContext.ExceptionHandled = true;
            }
        }

        public ActionResult SecurityExceptionResult()
        {
            if (_currentUser != null)
            {
                ConcurrentUserInfo.RemoveByUserName(CurrentUser.Username);
            }
            FormsAuthentication.SignOut();
            return View();
        }

        private IMembershipService _mebershipebershipService;

        public IMembershipService MembershipService
        {
            get { return _mebershipebershipService ?? (_mebershipebershipService = new MembershipService()); }
            set
            {
                _mebershipebershipService = value;
                SetCurrentUserViewBag();
            }
        }

        private void SetCurrentUserViewBag()
        {
            if (HttpContext != null && (MembershipService.IsAuthenticated))
            {

                ViewBag.CurrentUser = CurrentUser;
            }
        }

        public int? UserId
        {
            get
            {
                if (CurrentUser != null)
                {
                    return CurrentUser.Id;
                }
                else
                {
                    return null;
                }
            }
        }


        private User _currentUser;

        public bool IsCurrentUserNotNull { get { return _currentUser != null; } }

        public User CurrentUser
        {
            get
            {
                if (_currentUser == null)
                {
                    _currentUser = ConcurrentUserInfo.GetConcurrentUserInfoByGuid(User.Identity.Name);
                    if (_currentUser != null && _currentUser.ActiveClinicGroup == null)
                    {
                        using (var clinicGroupRepo = new Repository.Clinics.ClinicGroupRepository())
                        {
                            _currentUser.ActiveClinicGroup = clinicGroupRepo.GetItem(_currentUser.ActiveClinicGroupId);
                        }
                    }
                }
                if (_currentUser == null)
                {
                    Response.Redirect("/base/SecurityExceptionResult", true);
                }
                return _currentUser;
            }
        }


        public void UpdatCurrentUser(User user)
        {
            var cUser = ConcurrentUserInfo.ConcurrentUsers.Single(u => u.User.Id == user.Id);
            if (!CurrentUser.IsAdministrator)
            {
                user.ActiveClinicId = cUser.User.ActiveClinicId;
                user.ActiveClinicGroupId = cUser.User.ActiveClinicGroupId;
                // cUser.DefaultIssuerId = user.DefaultIssuerId;
            }

            cUser.User = user;
        }

        public bool IsPatientInCurrentClinic(int patientId)
        {
            return RapidVetUnitOfWork.PatientRepository.IsPatientInClinic(patientId, CurrentUser.ActiveClinicId);
        }

        public bool IsClientInCurrentClinic(int clientId)
        {
            return RapidVetUnitOfWork.ClientRepository.IsClientInClinic(CurrentUser.ActiveClinicId, clientId);
        }


        public bool IsClinicGroupMember(int clinicGroupId)
        {
            return CurrentUser.ClinicGroupId == null || CurrentUser.ClinicGroupId == clinicGroupId;
        }

        public bool IsSmsActive()
        {
            return !string.IsNullOrWhiteSpace(CurrentUser.ActiveClinicGroup.UnicellUserName) &&
                   !string.IsNullOrWhiteSpace(CurrentUser.ActiveClinicGroup.UnicellPassword);
        }

        public bool IsStikerActive()
        {
            return CurrentUser.ActiveClinicGroup.StikerColumns > 0 &&
                   CurrentUser.ActiveClinicGroup.StikerRows > 0 &&
                   CurrentUser.ActiveClinicGroup.StikerRowHight > 0;
        }

        public bool IsEmailActive()
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.EmailAddress);
        }

        public bool IsTreatmentStikerExist()
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.TreatmentStikerTemplate);
        }
        public bool IsTreatmentEmailExist()
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.TreatmentEmailSubject) &&
                   !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.TreatmentEmailTemplate);
        }
        public bool IsTreatmentSmsExist()
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.TreatmentSmsTemplate);
        }
        public bool IsClientStikerExist()
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.ClientsStikerTemplate);
        }
        public bool IsClientEmailExist() //for client reports
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.ClientsEmailSubject) &&
                   !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.ClientsEmailTemplate);
        }
        public bool IsClientSmsExist()
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.ClientsSmsTemplate);
        }
        public bool IsPersonalLetterExist()
        {
            return RapidVetUnitOfWork.LetterTemplatesRepository.IsPersonalLetterExist(CurrentUser.ActiveClinicId);
        }

        public bool IsFollowUpEmailExist()
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.FollowUpsEmailSubject) &&
                   !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.FollowUpsEmailTemplate);
        }

        public bool IsFollowUpSmsExist()
        {
            return !string.IsNullOrEmpty(CurrentUser.ActiveClinicGroup.FollowUpsSmsTemplate);
        }

        public ClientDetailsModel GetClientDetailsModelFromPatient(int patientId, string dtFrom = "01/01/2017", string dtTo = "31/12/2017", string isToShowMoney = "true")
        {
            var clientId = RapidVetUnitOfWork.PatientRepository.GetClientId(patientId);
            return GetClientDetailsModel(clientId);
        }

        public ClientDetailsModel GetClientDetailsModel(int clientId)
        {
            var client = RapidVetUnitOfWork.ClientRepository.GetClient(clientId);
            var model = AutoMapper.Mapper.Map<Client, ClientDetailsModel>(client);
            if (!model.Balance.HasValue)
            {
                model.Balance = 0;
            }
            model.NextClientAppointment = RapidVetUnitOfWork.CalenderRepository.GetNextClientAppointment(client.Id);            
            
            return model;
        }
        public int GetPatientNextEntryId(int patientId)
        {
            return RapidVetUnitOfWork.CalenderRepository.GetCalenderEntryId(patientId);
        }
        public int GetPatientNextWatchId(int patientId)
        {
            return RapidVetUnitOfWork.CalenderRepository.GetCalenderWatchId(patientId);
        }

        public ActionResult PatientName(int id)
        {

RapidVet.Web/Controllers/Settings/MedicationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Security;
using System.Web;
using System.Web.Mvc;
using RapidVet.Model.Visits;
using RapidVet.Repository;
using RapidVet.WebModels.Medications;

namespace RapidVet.Web.Controllers.Settings
{
    [Authorize]
    [ClinicGroupManager]
    public class MedicationController : BaseController
    {

        //
        // GET: /Medication/

        public ViewResult Index(bool print = false)
        {
            var medications =
                RapidVetUnitOfWork.MedicationRepository.GetClinicGroupMedications(CurrentUser.ActiveClinicGroupId);
            ViewBag.Print = print;
            return View(medications.ToList());
        }

        /// <summary>
        /// Get Action of Creat new Medication in the active clinic Group
        /// </summary>
        /// <returns>Eampty Creat Medication Modal</returns>
        public ActionResult Create()
        {
            return View();
        }


        /// <summary>
        /// Post Action of Creat new Medication in the active clinic Group
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Redirect to medication Index</returns>
        [HttpPost]
        public ActionResult Create(MedicationEditWebModel model)
        {
            if (ModelState.IsValid)
            {
                var medication = AutoMapper.Mapper.Map<MedicationEditWebModel, Medication>(model);
                medication.ClinicGroupId = CurrentUser.ActiveClinicGroupId;
                var status = RapidVetUnitOfWork.MedicationRepository.AddMedication(medication);
                if (status.Success)
                {
                    SetSuccessMessage();
                    return RedirectToAction("Index", "Medication");
                }
                else
                {
                    SetErrorMessage();
                    return View("Error");
                }
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult CreateFromVisit(MedicationEditWebModel model)
        {
            var medication = AutoMapper.Mapper.Map<MedicationEditWebModel, Medication>(model);
            medication.ClinicGroupId = CurrentUser.ActiveClinicGroupId;
            var status = RapidVetUnitOfWork.MedicationRepository.AddMedication(medication);
            if (status.Success)
            {
                status.ItemId = medication.Id;
                SetSuccessMessage();
            }
            else
            {
                SetErrorMessage();
            }

            return Json(status);
        }

        /// <summary>
        /// returns edit view of medication
        /// </summary>
        /// <param name="id">medicationId</param>
        /// <returns>ActionResult</returns>
        public ActionResult Edit(int id)
        {
            var medication = RapidVetUnitOfWork.MedicationRepository.GetMedication(id);
            if (medication.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException();
            }
            var model = AutoMapper.Mapper.Map<Medication, MedicationEditWebModel>(medication);
            return View(model);
        }


        /// <summary>
        /// handles post for previous actionResult
        /// </summary>
        /// <param name="model">MedicationEditWebModel</param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        public ActionResult Edit(MedicationEditWebModel model)
        {
            if (ModelState.IsValid)
            {
                var medication = RapidVetUnitOfWork.MedicationRepository.GetMedication(model.Id);
                if (medication.ClinicGroupId == CurrentUser.ActiveClinicGroupId)
                {
                    AutoMapper.Mapper.Map(model, medication);
                    medication.Updated = DateTime.Now;
                    var status = RapidVetUnitOfWork.MedicationRepository.Save(medication);
                    if (status.Success)
                    {
                        SetSuccessMessage();
                    }
                    else
                    {
                        SetErrorMessage();
                    }
                    if (status.Success)
                    {
                        return RedirectToAction("Index", "Medication");
                    }
                    return View("Error");
                }
                throw new SecurityException();
            }
            return View(model);
        }


        /// <summary>
        /// gets delete view for medication
        /// </summary>
        /// <param name="id">medicationId</param>
        /// <returns>PartialViewResult</returns>
        public PartialViewResult Delete(int id)
        {
            var medication = RapidVetUnitOfWork.MedicationRepository.GetMedication(id);
            if (medication.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException();
            }
            var model = AutoMapper.Mapper.Map<Medication, MedicationEditWebModel>(medication);
            return PartialView("_Delete", model);
        }

        /// <summary>
        /// handles post event for previous function
        /// </summary>
        /// <param name="id">medicationId</param>
        /// <param name="name">medication name</param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        public ActionResult Delete(int id, string name)
        {
            var medication = RapidVetUnitOfWork.MedicationRepository.GetMedication(id);
            if (medication.ClinicGroupId == CurrentUser.ActiveClinicGroupId)
            {
                medication.Active = false;
                var status = RapidVetUnitOfWork.MedicationRepository.Save(medication);
                if (status.Success)
                {
                    return RedirectToAction("Index", "Medication");
                }
                return View("Error");
            }
            throw new SecurityException();
        }


    }
}

RapidVet.Web/Views/Visit/Index.cshtml
@model RapidVet.WebModels.Clients.ClientDetailsModel
@{
    Layout = "~/Views/Shared/_PatientsLayout.cshtml";
    var patientId = Url.RequestContext.RouteData.Values["id"];

    var visitId = Request.Params["visitId"] ?? "0";
}
@section scripts
{
    <script>
        var maxInt = @int.MaxValue;
        var maxDecimal = @decimal.MaxValue;
    </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/App/Patients/CurrentVisit.js?v=" + typeof(RapidVet.Web.MvcApplication).Assembly.GetName().Version)"></script>
    <script type="text/javascript">
        $(document).ready(function () {
           // console.log("1");
            //  changes mouse cursor when highlighting loawer right of box
            $(document).on('mousemove', 'textarea', function(e) {
                var a = $(this).offset().top + $(this).outerHeight() - 16,	//	top border of bottom-right-corner-box area
                    b = $(this).offset().left + $(this).outerWidth() - 16;	//	left border of bottom-right-corner-box area
                $(this).css({
                    cursor: e.pageY > a && e.pageX > b ? 'nw-resize' : ''
                });
            })
           
            //  the following simple make the textbox "Auto-Expand" as it is typed in
            .on('keyup', 'textarea', function(e) {
                //  the following will help the text expand as typing takes place
                while($(this).outerHeight() < this.scrollHeight + parseFloat($(this).css("borderTopWidth")) + parseFloat($(this).css("borderBottomWidth"))) {
                    $(this).height($(this).height()+1);
                };
            });
        });
    </script>
}

<style>
    /*.btn-primary, .btn-warning {
        width: 150px;
    }*/

        .btn-primary.mini {
            width: 10px;
        }

    .validationMessage {
        color: red !important;
    }

    .simpleColorContainer {
        right: -10px;
    }
</style>

@section clientDetailsBar
{
    @Html.Partial("~/Views/Clients/_ClientDetailsBar.cshtml", Model)
}

@section patientDetailsBar
{
    @Html.Action("GetPatientDetailsBar", "Base", new { id = patientId })
}

<div class="form-inline">

    <input type="hidden" name="patientId" id="patientId" value="@patientId" />
    <input type="hidden" name="visitId" id="visitId" value="@visitId" />
    <input type="hidden" value="@ViewBag.ClientId" id="clientId" />
    <input type="hidden" value="@ViewBag.PatientId" id="patientId" />
    <input type="hidden" value="@ViewBag.VisitId" id="visitId" />
    <input type="hidden" value="@CurrentUser.IsClinicGroupManager" id="IsClinicGroupManager" />
    <div id="visitDiv">

        @Html.Partial("_GeneralData", Model)

        @*<div class="row control-group">
                <div class="span12">
                    <label>
                        <span>@RapidVet.Resources.Controllers.Views.PatientIndex.MainComplaint</span>
                        <textarea data-bind="value: mainComplaint" rows="1" cols="200"></textarea>
                    </label>
                </div>
            </div>*@

        <h2>@RapidVet.Resources.Controllers.Views.PatientIndex.Examinations</h2>
        <a data-bind="click: addBlankExamination" class="btn btn-primary">
            <i class="icon-plus"></i>
            @RapidVet.Resources.Controllers.Views.PatientIndex.AddExamination
        </a>
        <a data-bind="click: showExaminationsModal" class="btn btn-primary">
            <i class="icon-th-list"></i>
            @RapidVet.Resources.Visit.AddExaminationFromPriceList
        </a>
        <br />
        <br />
        <div>
            <div class="row control-group">
                @Html.Partial("_Examinations")
            </div>
        </div>


        <h2>@RapidVet.Resources.Controllers.Views.PatientIndex.Diagnoses</h2>
        <a data-bind="click: addBlankDiagnosis" class="btn btn-primary">
            <i class="icon-plus"></i>
            @RapidVet.Resources.Controllers.Views.PatientIndex.AddDiagnosis
        </a>
        <a data-bind="click: showDiagnosesModal" class="btn btn-primary">
            <i class="icon-th-list"></i>
            @RapidVet.Resources.Visit.AddDiagnosisFromList
        </a>
        <br />
        <br />
        <div class="row control-group">
            @Html.Partial("_Diagnoses")
        </div>

        <h2>@RapidVet.Resources.Controllers.Views.PatientIndex.Treatments</h2>
        <a data-bind="click: addBlankTreatment" class="btn btn-primary">
            <i class="icon-plus"></i>
            @RapidVet.Resources.Controllers.Views.PatientIndex.AddTreatment
        </a>
        <a data-bind="click: showTreatmentsModal" class="btn btn-primary">
            <i class="icon-th-list"></i>
            @RapidVet.Resources.Visit.AddTreatmentFromPriceList
        </a>
        <br />
        <br />
        <div class="row control-group">
            @Html.Partial("_Treatments")
        </div>


        <h2>@RapidVet.Resources.Controllers.Views.PatientIndex.Medications</h2>
        <a data-bind="click: showMedicationsModal" class="btn btn-primary">
            <i class="icon-th-list"></i>
            @RapidVet.Resources.Controllers.Views.PatientIndex.AddMedication
        </a>
        <a data-bind="click: showDangerousDrugsModel" class="btn btn-warning">
            <i class="icon-warning-sign"></i>
            &nbsp; @RapidVet.Resources.DangerousDrugs.Title
        </a>
        <input type="checkbox" data-bind="checked: printPrescriptionValidityComment" class="styled" />
        @RapidVet.Resources.Visit.ShowPrescriptionValidity
        <br />
        <br />
        <div class="row control-group">
            @Html.Partial("_Medications")
            @Html.Partial("_DangerousDrugs")
        </div>
    </div>
   
        <div>
            <h2> @RapidVet.Resources.Global.Comment</h2>
        </div>
        <div>
            <textarea style="width: 55%; background-color: #e6e6e6; border: ridge 1px #a8a8a8; height: 55px; margin-bottom: 10px;" data-bind="value: visitNote"></textarea>
        </div>
   
    <div data-bind="visible: active()">
        <input type="checkbox" data-bind="checked: closeVisit" class="styled" />
        @RapidVet.Resources.Visit.CloseVisit
    </div>
    <br />
    <br />
    <div>
        <a id="back" class="btn btn-inverse" href="@Url.Action("Patients", "Clients", new { id = Model.Id })">@RapidVet.Resources.Visit.CancelWithoutSaving</a>
        <a class="btn btn-primary" data-bind="click: saveVisit, visible: active()">
            <i class="icon-file"></i>
            @RapidVet.Resources.Global.Save
        </a>
        <a class="btn btn-primary" data-bind="click: saveAndPrint, visible: active()">
            <i class="icon-print"></i>
            @RapidVet.Resources.Visit.SaveAndPrintVisit
        </a>
        <a data-bind="click: saveAndPrintSubscription, visible: active()" class="btn btn-primary">
            <i class="icon-list-alt"></i>
            @RapidVet.Resources.Visit.SaveAndPrintPrescription
        </a>
    </div>
    <span class="validationMessage" id="validateSummary" style="display: none">@RapidVet.Resources.Controllers.Views.PatientIndex.CannotSave</span>
</div>

RapidVet.Web/Views/Visit/PrintPrescription.cshtml
@using RapidVet.Enums;
@model RapidVet.WebModels.Visits.PrescriptionModel
@{
    Layout = "~/Views/Shared/_PrintingLayout.cshtml";
}

<img src="/ClinicGroups/LogoImage" style="max-width: 100%; float: left;max-height: 150px;max-width: 150px;">

<div class="row">
    <div class="span4">
        <h3>@Html.DisplayFor(m => m.ClinicName)</h3>
        <span>@Html.DisplayFor(m => m.ClinicAddress)</span>
        <br />
        <span>טל': </span><span>@Html.DisplayFor(m => m.ClinicPhone)</span>
        <br />
        <span>פקס: </span><span>@Html.DisplayFor(m => m.ClinicFax)</span>
        <br />
        <span>@Html.DisplayFor(m => m.ClinicEmail)</span>
    </div>
    <div class="span4">&nbsp;</div>
    
</div>




<div class="row">
    <div style="display: block; position: relative; float: left; margin-left: 35px;"><b>תאריך: @DateTime.Now.ToShortDateString() </b></div>
    @if (Model.PrintComments)
    {
        <div class="row">
            <div class="span2">&nbsp;</div>
            <div class="span8" style="position:relative; margin:auto; text-decoration: underline;display:block; 
                                      text-align: center; font-size: 18px;font-weight:bold;">
                מרשם זה בתוקף ל-10 ימים בלבד
            </div>
            <div class="span2">&nbsp;</div>
        </div>
    }
   <br />
    <div class="span4">
        <span>שם הרופא המנפק:</span>
        <span>@Html.DisplayFor(m => m.DoctorName)</span>
        <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
        <span>מס' רשיון:</span>
        <span>@Html.DisplayFor(m => m.DoctorLicenseNumber)</span>
    </div>
    <div class="span4">&nbsp;</div>

</div>
<div class="row">
    <div class="span4">
        
            <span>שם הבעלים: </span><span>@Html.DisplayFor(m => m.ClientName)</span>
            <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <span>ת.ז: </span> <span>@Html.DisplayFor(m => m.ClientIdCard)</span>
        
        <br />
            <span>כתובת: </span><span>@Html.DisplayFor(m => m.ClientAddress)</span>
       <br />
            <span>שם בעל החיים: </span><span>@Html.DisplayFor(m => m.PatientName)</span>
    </div>
</div>


<div style="position: relative; display: block; float: left; direction: ltr; margin-left: 35px;">Rp.</div>
<br />
<br />
<br />
<table class="table table-bordered" style="width: 100%; margin: auto; vertical-align: middle;">

    <thead>
        <tr>
            <th style="width: 250px;">שם התרופה</th>
            <th style="text-align: center;width: 60px;">תצורה</th>
            <th style="text-align: center;width: 40px;">מנה</th>
            <th style="text-align: center;width: 60px;">מס' פעמים ביום</th>
            <th style="width: 90px;">משך זמן לקיחה בימים</th>
            <th style="text-align: center;width: 50px;">סך-הכל כמות</th>
            <th style="width: 150px;">הוראות שימוש</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.VisitMedications.Any())
        {
            foreach (var vm in Model.VisitMedications)
            {
            <tr>
                <td>@Html.DisplayFor(modelVm => vm.Name)</td>
                <td style="text-align: center;">@(((MedicationAdministrationType)vm.MedicationAdministrationTypeId).ToString())</td>
                <td style="text-align: center;">@Html.DisplayFor(modelVm => vm.Dosage)</td>
                <td style="text-align: center;">@Html.DisplayFor(modelVm => vm.TimesPerDay)</td>
                <td style="text-align: center;">@Html.DisplayFor(modelVm => vm.NumberOfDays)</td>
                <td style="text-align: center;">@Html.DisplayFor(modelVm => vm.OverallAmount)</td>
                <td>@Html.DisplayFor(modelVm => vm.Insturctions)</td>
            </tr>
            }
        }
    </tbody>
</table>

<br />
<div class="row">
    הערה: במקרה של הופעת פריחה, גירוד או כל תופעת לוואי אחרת, יש להפסיק את נטילת התרופה וליצור קשר עם הרופא המטפל
</div>


<div class="row">
    <div class="span4">
        &nbsp;
    </div>
    <div class="span4">&nbsp;</div>
    <div class="span4">
        <span>_______________</span>
        <br />
        @Html.DisplayFor(m => m.DoctorName)

    </div>
</div>