RapidVet.Web/Controllers/Office/FollowUpsController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using RapidVet.Enums;
using RapidVet.Helpers;
using RapidVet.Model.Clinics;
using RapidVet.Model.PatientFollowUp;
using RapidVet.Model.Patients;
using RapidVet.WebModels.PatientFollowUps;
using apidVet.WebModels.FollowUp;
using RestSharp;

namespace RapidVet.Web.Controllers
{
    public class FollowUpsController : BaseController
    {
        enum FollowUpsPrintOutput
        {
            Sms, Email
        }
        public ActionResult Index()
        {
            var docs = RapidVetUnitOfWork.ClinicRepository.GetClinicDoctors(CurrentUser.ActiveClinicId);
            if (docs == null)
                docs = new List<Model.Users.User>();

            docs.Insert(0, new Model.Users.User()
            {
                Id = -1,
                FirstName = "הכל"
            });
            ViewBag.Doctors = docs;
            ViewBag.Email = IsEmailActive() && IsFollowUpEmailExist();
            ViewBag.Sms = IsSmsActive() && IsFollowUpSmsExist();
            ViewBag.Letter = IsPersonalLetterExist();

            var from = DateTime.Now;
            var to = DateTime.Now;

            switch (CurrentUser.ActiveClinic.FollowUpTimeRange)
            {
                case FollowUpTimeRange.Days:
                    from = from.AddDays(CurrentUser.ActiveClinic.FollowUpPast * -1);
                    to = to.AddDays(CurrentUser.ActiveClinic.FollowUpFuture);
                    break;
                case FollowUpTimeRange.Months:
                    from = from.AddMonths(CurrentUser.ActiveClinic.FollowUpPast * -1);
                    to = to.AddMonths(CurrentUser.ActiveClinic.FollowUpFuture);
                    break;
            }

            ViewBag.From = from.ToShortDateString();
            ViewBag.To = to.ToShortDateString();
            return View();
        }


        public JsonResult GetFollowUps(string from, string to, bool includeInactivePatients, string docID)
        {
            var model = GetFollowUpsData(from, to, includeInactivePatients, docID);
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Create()
        {
            var defaultDate = DateTime.Now;
            switch (CurrentUser.ActiveClinic.DefaultFollowUpType)
            {
                case FollowUpTimeRange.Days:
                    defaultDate = defaultDate.AddDays(CurrentUser.ActiveClinic.DefaultFollowUpTime);
                    break;
                case FollowUpTimeRange.Months:
                    defaultDate = defaultDate.AddMonths(CurrentUser.ActiveClinic.DefaultFollowUpTime);
                    break;
            }
            var model = new FollowUp()
                {
                    DateTime = defaultDate,
                    UserId = CurrentUser.Id,
                };
            return View(model);
        }

        [HttpPost]
        public JsonResult Create(FollowUpWebModel model)
        {
            var date = StringUtils.ParseStringToDateTime(model.DateTime);
            if (date > DateTime.MinValue)
            {
                FollowUp followUp = new FollowUp()
                {
                    Created = DateTime.Now,
                    PatientId = model.PatientId,
                    DateTime = date,
                    Comment = model.Comment,
                    UserId = model.UserId
                };

                var status = RapidVetUnitOfWork.FollowUpRepository.Create(followUp);
                if (status.Success)
                {
                    SetSuccessMessage();
                }
                else
                {
                    SetErrorMessage();
                }

                return Json(status.Success);

            }

            return Json(false);
        }

        [HttpPost]
        public void CreateFromPatientFile(FollowUpWebModel model)
        {
            var date = StringUtils.ParseStringToDateTime(model.DateTime);
            if (date == DateTime.MinValue)
            {
                date = DateTime.Now;
            }
            if (date > DateTime.MinValue)
            {
                FollowUp followUp = new FollowUp()
                {
                    Created = DateTime.Now,
                    PatientId = model.PatientId,
                    DateTime = date,
                    Comment = model.Comment,
                    UserId = model.UserId
                };

                var status = RapidVetUnitOfWork.FollowUpRepository.Create(followUp);
                if (status.Success)
                {
                    SetSuccessMessage();
                }
                else
                {
                    SetErrorMessage();
                }



            }

        }

        [HttpPost]
        public ActionResult Update(string json)
        {
            if (!string.IsNullOrWhiteSpace(json))
            {
                var viewfollowUp = JsonConvert.DeserializeObject<FollowUpIndexModel>(json);
                var followUp = RapidVetUnitOfWork.FollowUpRepository.GetFollowUp(viewfollowUp.FollowUpId);
                followUp.Comment = viewfollowUp.Comment;
                if (!string.IsNullOrWhiteSpace(viewfollowUp.DateTime))
                {
                    var followupDate = StringUtils.ParseStringToDateTime(viewfollowUp.DateTime);
                    if (followupDate > DateTime.MinValue)
                    {
                        followUp.DateTime = followupDate;
                    }
                }

                if (viewfollowUp.DoctorId > 0)
                {
                    followUp.UserId = viewfollowUp.DoctorId;
                }
                followUp.Updated = DateTime.Now;
                var status = RapidVetUnitOfWork.Save();

                if (status.Success) { SetSuccessMessage(); }
                else { SetErrorMessage(); }

                return Json(status.Success);
            }
            SetErrorMessage("לא נשלח מעקב");
            return Json(false);
        }

        //id is followUp id
        [HttpPost]
        public JsonResult Delete(int id)
        {
            var status = RapidVetUnitOfWork.FollowUpRepository.Delete(id);
            if (status.Success)
            {
                SetSuccessMessage();
            }
            else
            {
                SetErrorMessage();
            }
            return Json(status.Success);
        }

        [HttpPost]
        public JsonResult RenewAll(int minDaysFromFollowUpWithoutAppointment, int remindersAddMonths)
        {
            var status = RapidVetUnitOfWork.FollowUpRepository.RenewAllFollowUps(CurrentUser.ActiveClinicId,
                                                                                 minDaysFromFollowUpWithoutAppointment,
                                                                                 remindersAddMonths);
            return Json(status);
        }

        [HttpPost]
        public JsonResult SendSMS(string clients, bool single = false)
        {
            var template = CurrentUser.ActiveClinicGroup.FollowUpsSmsTemplate;
            int messagesCounter = 0;
            int totalMessages = 0;
            if (!string.IsNullOrWhiteSpace(clients) && !string.IsNullOrWhiteSpace(template))
            {
                var data = GetClients(clients, single);

                foreach (var followUpIndexModel in data.Where(d => !string.IsNullOrWhiteSpace(d.CellPhone)))
                {
                    totalMessages++;
                    var followUp = RapidVetUnitOfWork.FollowUpRepository.GetFollowUp(followUpIndexModel.FollowUpId);
                    var nvc = GetNvcResults(followUp);
                    var message = GetTempalteWithData(template, followUpIndexModel);//RapidVetUnitOfWork.LetterTemplatesRepository.FormatString(nvc, template);
                    var sms = new Unicell.Sms(CurrentUser.ActiveClinicGroup.UnicellUserName,
                                              CurrentUser.ActiveClinicGroup.UnicellPassword,
                                              followUpIndexModel.CellPhone, message, string.IsNullOrWhiteSpace(CurrentUser.ActiveClinicGroup.SignatureSmsTemplate) ? "" : CurrentUser.ActiveClinicGroup.SignatureSmsTemplate);
                    var sendResult = sms.Send();
                    if (sendResult)
                    {
                        RapidVetUnitOfWork.MessageDistributionRepository.Increment(CurrentUser.ActiveClinicId, 1, MessageType.Sms);
                        string logMessage = string.Format("{0}: {1}<br />{2}: {3}<br />{4}: {5}<br />{6}: {7}<br />{8}: {9}",
                                                                Resources.Auditing.SendingModule, Resources.Auditing.FollowUps,
                                                                Resources.Auditing.ClientName, followUpIndexModel.ClientName,
                                                                Resources.Auditing.PhoneNumber, followUpIndexModel.CellPhone,
                                                                Resources.Auditing.SmsContent, message,
                                                                Resources.Auditing.ReturnCode, sendResult);

                        RapidVetUnitOfWork.AuditingRepository.Audit(CurrentUser, Resources.Auditing.SmsSent, logMessage, "");
                        messagesCounter += 1;
                    }
                    else
                    {
                        SetErrorMessage("אירעה שגיאה בשליחת ההודעות");
                        return null;
                    }
                }
                //SetSuccessMessage("ההודעות נשלחו בהצלחה");

RapidVet.Web/Controllers/Settings/AnimalColorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Web;
using System.Web.Mvc;
using RapidVet.Helpers;
using RapidVet.Model;
using RapidVet.Model.Patients;
using RapidVet.Repository.Patients;
using RapidVet.WebModels.Patients;

namespace RapidVet.Web.Controllers
{
    [ClinicGroupManager]
    public class AnimalColorsController : BaseController
    {
        public ActionResult Index()
        {
            var colors = RapidVetUnitOfWork.AnimalColorRepository.GetList(CurrentUser.ActiveClinicGroupId);
            var model = colors.AnimalColors.Where(c => c.Active).Select(AutoMapper.Mapper.Map<AnimalColor, AnimalColorModel>).ToList();
            return View(model);
        }

        //id is clinicGroupId
        public PartialViewResult Create()
        {
            var model = new AnimalColorModel()
                {
                    ClinicGroupId = CurrentUser.ActiveClinicGroupId
                };
            return PartialView("_Create", model);

        }

        [HttpPost]
        public ActionResult Create(AnimalColorModel model)
        {


            var color = AutoMapper.Mapper.Map<AnimalColorModel, AnimalColor>(model);
            color.Active = true;
            color.Id = 0;
            color.ClinicGroupId = CurrentUser.ActiveClinicGroupId;
            var status = RapidVetUnitOfWork.AnimalColorRepository.Create(color);
            return RedirectToAction("Index", "AnimalColors");

        }

        //id is animalColorId
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var color = RapidVetUnitOfWork.AnimalColorRepository.GetItem(id);
            if (color.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException(Resources.Exceptions.AccessDenied);
            }
            var model = AutoMapper.Mapper.Map<AnimalColor, AnimalColorModel>(color);
            return PartialView("_Edit", model);
        }

        //id is animalColorId
        [HttpPost]
        public ActionResult Edit(AnimalColorModel model)
        {

            var color = RapidVetUnitOfWork.AnimalColorRepository.GetItem(model.Id);
            if (color.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException(Resources.Exceptions.AccessDenied);
            }
            AutoMapper.Mapper.Map(model, color);

            var status = RapidVetUnitOfWork.AnimalColorRepository.Update(color);
            return RedirectToAction("Index", "AnimalColors");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var color = RapidVetUnitOfWork.AnimalColorRepository.GetItem(id);
            if (color.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException(Resources.Exceptions.AccessDenied);
            }
            var model = AutoMapper.Mapper.Map<AnimalColor, AnimalColorModel>(color);
            return PartialView("_Delete", model);
        }

        [HttpPost]
        public ActionResult Delete(AnimalColorModel model)
        {
            var color = RapidVetUnitOfWork.AnimalColorRepository.GetItem(model.Id);
            if (color.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException(Resources.Exceptions.AccessDenied);
            }
            color.Active = false;
            var status = RapidVetUnitOfWork.AnimalColorRepository.Update(color);
            return RedirectToAction("Index", "AnimalColors");

        }
    }
}

RapidVet.Web/Controllers/Settings/AnimalKindsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;
using System.Web.Mvc;
using RapidVet.Helpers;
using RapidVet.Model;
using RapidVet.Model.Patients;
using RapidVet.Repository.Patients;
using RapidVet.WebModels.Patients;

namespace RapidVet.Web.Controllers
{
    [ClinicGroupManager]
    public class AnimalKindsController : BaseController
    {

        public ActionResult Index()
        {
            var kinds = RapidVetUnitOfWork.AnimalKindRepository.GetList(CurrentUser.ActiveClinicGroupId);
            var model = kinds.Select(AutoMapper.Mapper.Map<AnimalKind, AnimalKindModel>).ToList();
            return View(model);
        }

        [HttpGet]
        public PartialViewResult Create()
        {
            var model = new AnimalKindModel()
                {
                    ClinicGroupId = CurrentUser.ActiveClinicGroupId
                };
            ViewBag.icons = RapidVetUnitOfWork.AnimalKindRepository.GetIcons();
            return PartialView("_Create", model);
        }

        [HttpPost]
        public ActionResult Create(AnimalKindModel model)
        {

            model.ClinicGroupId = CurrentUser.ActiveClinicGroupId;
            var kind = AutoMapper.Mapper.Map<AnimalKindModel, AnimalKind>(model);
            kind.Id = 0;
            kind.Active = true;
            var status = RapidVetUnitOfWork.AnimalKindRepository.Create(kind);
            return RedirectToAction("Index", "AnimalKinds");
        }

        //id is animalKindId
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var kind = RapidVetUnitOfWork.AnimalKindRepository.GetItem(id);
            if (kind.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException(Resources.Exceptions.AccessDenied);
            }
            ViewBag.icons = RapidVetUnitOfWork.AnimalKindRepository.GetIcons();
            var model = AutoMapper.Mapper.Map<AnimalKind, AnimalKindModel>(kind);
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(AnimalKindModel model)
        {

            var kind = RapidVetUnitOfWork.AnimalKindRepository.GetItem(model.Id);
            if (kind.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException(Resources.Exceptions.AccessDenied);
            }
            AutoMapper.Mapper.Map(model, kind);
            var status = RapidVetUnitOfWork.AnimalKindRepository.Update(kind);
            return RedirectToAction("Index", "AnimalKinds");

        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var kind = RapidVetUnitOfWork.AnimalKindRepository.GetItem(id);
            if (kind.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException(Resources.Exceptions.AccessDenied);
            }
            var model = AutoMapper.Mapper.Map<AnimalKind, AnimalKindModel>(kind);
            return PartialView("_Delete", model);
        }

        [HttpPost]
        public ActionResult Delete(AnimalKindModel model)
        {
            var kind = RapidVetUnitOfWork.AnimalKindRepository.GetItem(model.Id);
            if (kind.ClinicGroupId != CurrentUser.ActiveClinicGroupId)
            {
                throw new SecurityException(Resources.Exceptions.AccessDenied);
            }
            var status = RapidVetUnitOfWork.AnimalKindRepository.Delete(model.Id);
            return RedirectToAction("Index", "AnimalKinds");
        }
    }
}

RapidVet.Web/Views/FollowUps/Create.cshtml
@model RapidVet.Model.PatientFollowUp.FollowUp
@{
    int defaultDr = CurrentUser.DefaultDrId.HasValue ? CurrentUser.DefaultDrId.Value : 0;
}
@section breadcrumb
{
    <li><a href="/">@RapidVet.Resources.BreadCrums.Main</a>
        <span class="divider">&gt;</span>
    </li>
    <li><@CurrentUser.ActiveClinic.Name
        <span class="divider">&gt;</span>
    </li>
    <li class="active">מעקבים</li>
}

@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Scripts/App/FollowUps/Create.js?v=" + typeof(RapidVet.Web.MvcApplication).Assembly.GetName().Version)"></script>
}

<style type="text/css">
    .validationMessage{
        color: red !important;
        float: none !important;
    }
</style>

@*@using (Html.BeginForm("Create", "FollowUps", FormMethod.Post, new { @class = "form-inline", data_bind="submit: isValid" }))
{*@
    @*<input type="hidden" name="patient_id" data-bind="value: patientId" />*@
    @*<input type="hidden" name="userId" data-bind="value: doctorId" />*@
<div class="form-inline">
    <input type="hidden" id="defaultDr" name="defaultDr" value="@defaultDr" />

    <div class="row control-group">
        <div class="span2">
            <label style="height: 24px;">לקוח</label>
        </div>
        <div style="display:inline-block;">
            <label style="width: 220px; margin-right:18px;">
                <input type="text" class="client-search search-query" style="border:1px solid gray; width: 190px;padding-top: 3px;margin-bottom: 0px;" placeholder="@RapidVet.Resources.Global.Search" />
            </label>
            <label class="no-results" style="display:inline;right: 15px; position: relative;"> לא נמצאו תוצאות</label>
        </div>
        @*<div class="span10">
            <label>
                <select data-bind="value: clientId, options: clients, optionsCaption: 'בחר..', optionsText: 'Text', optionsValue: 'Value'"></select>
            </label>
        </div>*@
    </div>

    <div class="row control-group">
        <div class="span2">
            <label style="height: 24px;">חיה</label>
        </div>
        <div class="span10">
            <label>
                <select data-bind="value: patientId, options: patients, optionsCaption: 'בחר..', optionsText: 'Text', optionsValue: 'Value'"></select>
            </label>
        </div>
    </div>

    <div class="row control-group">
        <div class="span2">
            <label style="height: 24px;">תאריך</label>
        </div>
        <div class="span10">
            <label style="width:233px;">
                @Html.TextBox("DateTime", Model.DateTime.ToShortDateString(), new {  @readonly = "readonly", data_bind = "datepicker: date" })
            </label>
        </div>
    </div>

    <div class="row control-group">
        <div class="span2">
            <label style="height: 40px;">הערה</label>
        </div>
        <div class="span10">
            <label>
                @Html.TextAreaFor(m => m.Comment, new { data_bind = "value: comments" })
            </label>
        </div>
    </div>

    <div class="row control-group">
        <div class="span2">
            <label style="height: 24px;">רופא</label>
        </div>
        <div class="span10">
            <label>
                <select data-bind="value: doctorId, options: doctors, optionsCaption: 'בחר..', optionsText: 'Text', optionsValue: 'Value'"></select>
            </label>
        </div>
    </div>

    <div class="control-group" style="text-align:left;">
        <button type="submit" class="btn btn-primary" data-bind="click: submitForm" style=" width: 150px;">
            @*<i class="icon-ok"></i>*@<img src="/Content/img/RapidVet/ok-v.png">
        </button>
    </div>

    @*@Muze.OkButton()*@
    @* } *@

</div>

RapidVet.Web/Views/FollowUps/Letter.cshtml
@{
    if (ViewBag.Print)
    {
        Layout = "~/Views/Shared/_PrintingLayout.cshtml";
    }
}


@if (!ViewBag.Print)
{

    <a class="btn btn-primary btn-large" href="@ViewBag.PrintUrl">
        <i class="icon-print"></i>
        הדפס
    </a>
    <a class="btn btn-inverse btn-large" onclick="window.close();">
        <i class="icon-remove"></i>
        ביטול
    </a>
}

<div>
    @Html.Raw(ViewBag.Letter)
</div>

RapidVet.Web/Views/FollowUps/Settings.cshtml
@model RapidVet.WebModels.PatientFollowUps.FollowUpSettingsModel
@{
    Layout = "~/Views/Shared/_ClinicSettingsLayout.cshtml";
}

<h2>הגדרות מעקבים</h2>
<br />
<br />
@using (Html.BeginForm("Settings", "FollowUps", FormMethod.Post, new { @class = "form-inline" }))
{
    <h3>חתך ברירת מחדל</h3>
    <div class="control-group row-fluid">

        <div class="span2">
            <label>סוג </label>
        </div>
        <div class="span9">
            <label>
                @Html.EditorFor(m => m.FollowUpTimeRangeId)
            </label>
        </div>
    </div>
    
    <div class="row-fluid control-group">
        <div class="span2">
            <label>כמות אחורה</label>
        </div>
        <div class="span3">
            <label>@Html.EditorFor(m => m.FollowUpPast)</label>
        </div>
        <div class="span2">
            <label>כמות קדימה</label>
        </div>
        <div class="span3">
            <label>@Html.EditorFor(m => m.FollowUpFuture)</label>
        </div>
    </div>
    
    <h3>ברירת מחדל למעקב</h3>
    <div class="row-fluid control-group">
        <div class="span2">
            <label>סוג</label>
        </div>
        <div class="span9">
            <label>
                @Html.EditorFor(m => m.DefaultFollowUpTypeId)
            </label>
        </div>
    </div>
    
    <div class="row-fluid control-group">
        <div class="span2">
            <label>כמות קדימה</label>
        </div>
        <div class="span9">
            <label>@Html.EditorFor(m => m.DefaultFollowUpTime)</label>
        </div>
    </div>

    
    <div class="row control-group">
        <div class="span4">
            &nbsp;
        </div>
        <div class="span7">
            @Html.EditorFor(m => m.AutomaticallySetFollowUpsAfterVisit)
            צור מעקב אוטומטית לאחר ביקור
        </div>
    </div>
    
    <div class="row control-group">
        <div class="span4">
            &nbsp;
        </div>
        <div class="span7">
            @Html.EditorFor(m => m.ShowFollowUpsInPatientHistory)
            הצג מעקבים בהסטוריית חיה
        </div>
    </div>
    
    @Muze.OkButton()

}